### PR TITLE
Update dev.js

### PR DESCRIPTION
**Pull request by ghost**
added dev popup while giving dev it popups for the target user

### CODE REVIEW

**Comment by ghost** [comment]
same for vip.js

**Comment by ghost** [comment]
guys i also create a gymbadge system but i dont want it to be public if u guys have any private repo then let me know

**Comment by ghost** [comment]
also i can also add that title code :dancers:  but dont want that public

**Comment by LegacyEcho** [comment]
Accepted! :+1:

**Comment by ghost** [comment]
bro
i have title.js too thats the newly version created by me

**Comment by ghost** [comment]
and do it for vip.js too i added it in there too

**Pull request merged**
