### PR TITLE
Update poll.js

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by CharizardtheFireMage** [comment]
Why would you want to use `let` a lot, it isn't useful a lot. Adding color might be good, but then it isn't needed to have Strict mode

**Comment by CharizardtheFireMage** [comment]
Also that is a good idea to use `this.runBroadcast`.

**Comment by LegacyEcho** [comment]
hmmface

**Comment by LegacyEcho** [comment]
Closed by mistake :p

**Pull request closed without merging**
