### PR TITLE
Setup: Bigger Polls

### PR DESCRIPTION
**Pull request by LegacyEcho**
Allow bigger polls for tiers. Not sure if I counted right tho feelsnv

### CODE REVIEW

**Comment by ghost** [comment]
the error message isnt in sync with this change, granted this shouldn't be that big of a deal, but should be fixed too none the less

**Comment by LegacyEcho** [comment]
Fixed the error message. The only reason I am changing the max limit is because I saw a few people complain about this in lobby.

**Comment by Flouride** [comment]
Can you merge these into one commit?

**Comment by LegacyEcho** [comment]
I found a different poll so this pr is useless now.

**Comment by LegacyEcho** [comment]
This pr won't close dafuq

**Pull request closed without merging**
