### PR TITLE
added shoppm , shopdeclare  , custom dice game layout

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LegacyEcho** [comment]
Why have a shop declare? That way a user declare what ever they want.

**Comment by ghost** [comment]
yes
for advertising events or for advertising their leagues
or advertising bigbuck tour in their rooms..
so it can be usefull

**Comment by LegacyEcho** [comment]
They could also declare porn

**Comment by ghost** [comment]
lol
then perma ban
XD

**Comment by LegacyEcho** [comment]
It doesn't erase the fact that they did it the server would ending up getting in trouble if it were reported.

**Comment by ghost** [comment]
its a crime by posting stufflike that on a server (cyber crime) so i think they can understand

**Comment by LegacyEcho** [comment]
Not ever user listens to the rules.

**Comment by ghost** [comment]
we have to try that feature was on origin too .. so lets give a chance

**Pull request merged**
