### PR TITLE
Create title.js

### PR DESCRIPTION
**Pull request by Lord-Haji**

### CODE REVIEW

**Comment by CharizardtheFireMage** [comment]
Where is deletetitle? And I love how you incorrectly use this code (since it was a setabout code made by aakash).

**Comment by LegacyEcho** [comment]
LOL rejected

**Comment by Lord-Haji** [comment]
ugh it wasnt bro
U can ask him

**Comment by ghost** [comment]
Man haji is using my codes for alpha..
That title and profile plugin was created my mee..
And the its not also the new one i created the new one that contains delete title too..
Haji stop using my codes like this

**Comment by CharizardtheFireMage** [comment]
GG LOL

**Comment by ghost** [comment]
XD

**Pull request closed without merging**
