### PR TITLE
Title Setup

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LegacyEcho** [comment]
> This branch has conflicts that must be resolved

**Comment by ghost** [comment]
i solved it

**Comment by ghost** [comment]
add it now i send the code to otami

**Comment by LegacyEcho** [comment]
Just fix it here

**Comment by ghost** [comment]
fix wat it was already fixed
u can see on test server

**Comment by LegacyEcho** [comment]
> This branch has conflicts that must be resolved

**Comment by ghost** [comment]
add it now ...
we dont want the new code to be public

**Pull request closed without merging**
